manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: refil
      url-base: https://github.com/refil
    - name: Fortikeco
      url-base: https://github.com/fortikeco
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: refil
      revision: mwave
      import: app/west.yml
    - name: MWave-zephyr-module
      remote: Fortikeco
      import: config/west.yml
      revision: main
    - name: zmk-settings-reset-bootloader-module
      remote: refil
      revision: main
    - name: position-trigger
      url: https://github.com/ReFil/refil-zmk-behaviour-modules
      revision: key-position-trigger
  self:
    path: config
